version: '3.8'

volumes:
  mysql-volume:

services:
  api:
    build:
      context: .
      dockerfile: ./.docker/dev/node/Dockerfile
    volumes:
      - ./backend/:/app:cached
    tty: true
    ports:
      - ${API_PORT}:3000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./.docker/dev/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
