name: Deploy Production iOS

on:
  push:

jobs:
  build_ios:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
