name: microCMS-trigger
on:
  repository_dispatch:
    types: [post]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo A
        run: cat ${{ github.event }}

      - name: Echo B
        run: cat ${{ github.event.client_payload }}
    
      - name: Echo C
        run: cat ${{ github.event_path }}